# Generated by Django 3.2.7 on 2021-09-04 20:31

from django.db import migrations, models
import django.db.models.deletion
import icoapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_number_of_token_available', models.IntegerField()),
                ('bidding_window_open', models.DateTimeField()),
                ('bidding_window_closed', models.DateTimeField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bidding_price', models.FloatField(validators=[icoapp.models.validate_bid_tokens])),
                ('number_of_tokens', models.IntegerField(validators=[icoapp.models.validate_bid_tokens])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icoapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_token_received', models.IntegerField()),
                ('bid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bid_object', to='icoapp.bid')),
            ],
        ),
    ]
