# Generated by Django 3.2.7 on 2021-09-02 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Monitor',
            new_name='BidMonitor',
        ),
    ]
