# Generated by Django 3.2.7 on 2021-09-02 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0002_rename_monitor_bidmonitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bidmonitor',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='allocation',
            name='bidding_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icoapp.bid'),
        ),
    ]
