# Generated by Django 3.2.7 on 2021-09-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0003_auto_20210902_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='bidding_object',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='icoapp.bid'),
        ),
    ]
