# Generated by Django 3.2.7 on 2021-09-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0004_alter_allocation_bidding_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='bidding_object',
        ),
        migrations.AddField(
            model_name='allocation',
            name='bid_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid_object', to='icoapp.bid'),
            preserve_default=False,
        ),
    ]
