# Generated by Django 3.2.7 on 2021-09-02 22:31

from django.db import migrations, models
import icoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('icoapp', '0005_auto_20210902_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='number_of_tokens',
            field=models.IntegerField(validators=[icoapp.models.validate_bid_tokens]),
        ),
    ]
